version: '2'
networks:
  lb_web:
    external: true
  back:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.2.1.0/30
services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - VIRTUAL_HOST
    networks:
    - back
    - lb_web
  app:
    image: indiehosters/discourse
    volumes:
      - ./data/assets:/home/discourse/discourse/public/assets
      - ./data/uploads:/home/discourse/discourse/public/uploads
      - ./data/backups:/home/discourse/discourse/public/backups
    env_file:
      - ./env
    environment:
      - DISCOURSE_HOSTNAME=$VIRTUAL_HOST
    networks:
    - back
  sidekiq:
    image: indiehosters/discourse
    command: bundle exec sidekiq -q critical -q default -q low -v
    env_file:
      - ./env
    environment:
      - DISCOURSE_HOSTNAME=$VIRTUAL_HOST
    volumes_from:
      - app
    networks:
    - back
  postgres:
    image: postgres:9.4.8
    env_file:
      - ./env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
    - back
  redis:
    image: redis:3
    networks:
    - back
